'use client';

import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';

export function DownloadReport({ reportContent, imagePreview }: { reportContent: string, imagePreview: string | null }) {

  const handleDownloadPdf = async () => {
    const doc = new jsPDF('p', 'pt', 'a4');
    const margin = 40;
    const footerHeight = 60; // Estimated height of the footer
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const usableWidth = pageWidth - margin * 2;
    const usableHeight = pageHeight - margin * 2 - footerHeight; // Reserve space for footer
    let y = margin;
    
    // Helper to add footer to every page
    const addFooter = (docInstance: jsPDF) => {
        const pageCount = docInstance.internal.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            docInstance.setPage(i);
            const footerY = pageHeight - margin - footerHeight;

            docInstance.setFontSize(8);
            docInstance.setFont("helvetica", "bold");
            docInstance.text('AI Accuracy Disclaimer', margin, footerY + 10, { align: 'left' });
            
            docInstance.setFont("helvetica", "normal");
            const disclaimerText = "This report was generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.";
            const splitDisclaimer = docInstance.splitTextToSize(disclaimerText, usableWidth);
            docInstance.text(splitDisclaimer, margin, footerY + 22);
            
            const creatorText = "Created by Manuel M. in 2025 as a side hustle.";
            docInstance.text(creatorText, pageWidth / 2, pageHeight - margin + 10, { align: 'center'});
        }
    };

    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text('XRay Insights - Diagnostic Report', pageWidth / 2, y, { align: 'center' });
    y += 30;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: 'center' });
    y += 30;

    if (imagePreview) {
        try {
            const img = new Image();
            img.src = imagePreview;
            await new Promise(resolve => {
                img.onload = resolve;
            });
            const imgProps = doc.getImageProperties(img);
            const aspectRatio = imgProps.width / imgProps.height;
            let imgWidth = usableWidth * 0.6; // 60% of usable width
            let imgHeight = imgWidth / aspectRatio;
            
            const maxHeight = pageHeight * 0.3; // max 30% of page height
            if (imgHeight > maxHeight) {
                imgHeight = maxHeight;
                imgWidth = imgHeight * aspectRatio;
            }

            if (y + imgHeight > usableHeight) {
                doc.addPage();
                y = margin;
            }
            
            const x = (pageWidth - imgWidth) / 2;
            doc.addImage(img, 'PNG', x, y, imgWidth, imgHeight);
            y += imgHeight + 20;
        } catch (e) {
            console.error("Error adding image to PDF:", e);
        }
    }

    const lines = reportContent.split('\n');
    lines.forEach(line => {
        let isHeader = false;
        let text = line;

        if (line.startsWith('## ')) {
            isHeader = true;
            text = line.substring(3);
        } else {
            text = line.replace(/-\s\*\*(.*?)\*\*: /g, '$1: ').replace(/\*\*/g, '');
        }
        
        const splitText = doc.splitTextToSize(text, usableWidth);
        const textHeight = (splitText.length * (isHeader ? 14 : 10)) + (isHeader ? 15 : 6);

        if (y + textHeight > usableHeight) {
            doc.addPage();
            y = margin;
        }

        if (isHeader) {
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            y += 10;
            doc.text(splitText, margin, y);
            y += (splitText.length * 14) + 5;
            doc.line(margin, y - 8, margin + usableWidth, y - 8);
            y += 5;
        } else {
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(splitText, margin, y);
            y += (splitText.length * 10) + 6;
        }
    });

    addFooter(doc);

    doc.save('diagnostic-report.pdf');
  };

  return (
    <Button variant="outline" size="sm" onClick={handleDownloadPdf}>
      <Download className="mr-2" />
      Download as PDF
    </Button>
  );
}
